/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./components/DashBoard/ActionCard.vue')['default']
    AddButton: typeof import('./components/AddButton.vue')['default']
    AppFooter: typeof import('./components/Footer/AppFooter.vue')['default']
    CategoriaCrud: typeof import('./components/Categorias/CategoriaCrud.vue')['default']
    DashBoard: typeof import('./components/DashBoard/DashBoard.vue')['default']
    EstoqueCard: typeof import('./components/DashBoard/EstoqueCard.vue')['default']
    FornecedorForm: typeof import('./components/Fornecedores/FornecedorForm.vue')['default']
    FornecedorTable: typeof import('./components/Fornecedores/FornecedorTable.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    HeaderAppBar: typeof import('./components/Header/HeaderAppBar.vue')['default']
    HeaderDrawer: typeof import('./components/Header/HeaderDrawer.vue')['default']
    HeaderUserMenu: typeof import('./components/Header/HeaderUserMenu.vue')['default']
    LoginForm: typeof import('./components/Login/LoginForm.vue')['default']
    LoteForm: typeof import('./components/Lotes/LoteForm.vue')['default']
    LoteTable: typeof import('./components/Lotes/LoteTable.vue')['default']
    MarcasCrud: typeof import('./components/Marcas/MarcasCrud.vue')['default']
    MovimentacaoForm: typeof import('./components/Movimentacoes/MovimentacaoForm.vue')['default']
    MovimentacaoTable: typeof import('./components/Movimentacoes/MovimentacaoTable.vue')['default']
    MovimentacoesTable: typeof import('./components/DashBoard/MovimentacoesTable.vue')['default']
    ProductForm: typeof import('./components/Produtos/ProductForm.vue')['default']
    ProductTable: typeof import('./components/Produtos/ProductTable.vue')['default']
    ProdutosListCard: typeof import('./components/DashBoard/ProdutosListCard.vue')['default']
    ProfileCard: typeof import('./components/Profile/ProfileCard.vue')['default']
    RedirectButton: typeof import('./components/redirectButton.vue')['default']
    RelatorioEstoqueCritico: typeof import('./components/Estoque/RelatorioEstoqueCritico.vue')['default']
    RelatorioValidadeProxima: typeof import('./components/Estoque/RelatorioValidadeProxima.vue')['default']
    ReportCard: typeof import('./components/DashBoard/ReportCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StockTable: typeof import('./components/Estoque/StockTable.vue')['default']
    UserForm: typeof import('./components/Usuarios/UserForm.vue')['default']
    UserTable: typeof import('./components/Usuarios/UserTable.vue')['default']
  }
}
