/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Categorias/': RouteRecordInfo<'/Categorias/', '/Categorias', Record<never, never>, Record<never, never>>,
    '/Estoque/': RouteRecordInfo<'/Estoque/', '/Estoque', Record<never, never>, Record<never, never>>,
    '/Fornecedores/': RouteRecordInfo<'/Fornecedores/', '/Fornecedores', Record<never, never>, Record<never, never>>,
    '/Fornecedores/novo': RouteRecordInfo<'/Fornecedores/novo', '/Fornecedores/novo', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/lotes/': RouteRecordInfo<'/lotes/', '/lotes', Record<never, never>, Record<never, never>>,
    '/lotes/novo': RouteRecordInfo<'/lotes/novo', '/lotes/novo', Record<never, never>, Record<never, never>>,
    '/Marcas/': RouteRecordInfo<'/Marcas/', '/Marcas', Record<never, never>, Record<never, never>>,
    '/Movimentacoes/': RouteRecordInfo<'/Movimentacoes/', '/Movimentacoes', Record<never, never>, Record<never, never>>,
    '/Movimentacoes/nova': RouteRecordInfo<'/Movimentacoes/nova', '/Movimentacoes/nova', Record<never, never>, Record<never, never>>,
    '/Produtos/': RouteRecordInfo<'/Produtos/', '/Produtos', Record<never, never>, Record<never, never>>,
    '/Produtos/novo': RouteRecordInfo<'/Produtos/novo', '/Produtos/novo', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/Relatorios/criticos': RouteRecordInfo<'/Relatorios/criticos', '/Relatorios/criticos', Record<never, never>, Record<never, never>>,
    '/Relatorios/vencimentos': RouteRecordInfo<'/Relatorios/vencimentos', '/Relatorios/vencimentos', Record<never, never>, Record<never, never>>,
    '/Usuarios/': RouteRecordInfo<'/Usuarios/', '/Usuarios', Record<never, never>, Record<never, never>>,
    '/Usuarios/novo': RouteRecordInfo<'/Usuarios/novo', '/Usuarios/novo', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/Categorias/index.vue': {
      routes: '/Categorias/'
      views: never
    }
    'src/pages/Estoque/index.vue': {
      routes: '/Estoque/'
      views: never
    }
    'src/pages/Fornecedores/index.vue': {
      routes: '/Fornecedores/'
      views: never
    }
    'src/pages/Fornecedores/novo.vue': {
      routes: '/Fornecedores/novo'
      views: never
    }
    'src/pages/home.vue': {
      routes: '/home'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/lotes/index.vue': {
      routes: '/lotes/'
      views: never
    }
    'src/pages/lotes/novo.vue': {
      routes: '/lotes/novo'
      views: never
    }
    'src/pages/Marcas/index.vue': {
      routes: '/Marcas/'
      views: never
    }
    'src/pages/Movimentacoes/index.vue': {
      routes: '/Movimentacoes/'
      views: never
    }
    'src/pages/Movimentacoes/nova.vue': {
      routes: '/Movimentacoes/nova'
      views: never
    }
    'src/pages/Produtos/index.vue': {
      routes: '/Produtos/'
      views: never
    }
    'src/pages/Produtos/novo.vue': {
      routes: '/Produtos/novo'
      views: never
    }
    'src/pages/profile.vue': {
      routes: '/profile'
      views: never
    }
    'src/pages/Relatorios/criticos.vue': {
      routes: '/Relatorios/criticos'
      views: never
    }
    'src/pages/Relatorios/vencimentos.vue': {
      routes: '/Relatorios/vencimentos'
      views: never
    }
    'src/pages/Usuarios/index.vue': {
      routes: '/Usuarios/'
      views: never
    }
    'src/pages/Usuarios/novo.vue': {
      routes: '/Usuarios/novo'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
